### PR TITLE
[fix] Improper TypeScript importation with explicitly named .d.ts file and "type": "module" conversion

### PR DESCRIPTION
**Pull request by j4mesli**
Utilized <a href="https://github.com/Danetag/ntc-ts/pull/24">PR</a> for issue #23 as code-base to implement fix to issue described in issue.

Addresses issue by:

- creating `ntc-ts.ts` file so module `ntc-ts` is created on build of project
- updated `package.json` with `type: module,` to specify how Node.js should <a href="https://nodejs.org/api/packages.html">interpret the root.</a>

Now, the importation as specified in the README will work as intended. You can also import with the following to utilize the library's full capabilities:

```ts
import * as ntc from 'ntc-ts';

ntc.initColor(ntc.ORIGINAL_COLOR);
ntc.getColorName('#546a80'); // returns object { exactMatch: false, name: 'Blue Bayoux', rgb: '#496679' }
```

### CODE REVIEW

**Comment by Danetag** [comment]
@j4mesli Thanks for taking a crack at it!

Not sure why we need to duplicate `src/index.ts` to `src/ntc-ts.ts`, shouldn't the `type: module` fix it already on my [latest branch](https://github.com/Danetag/ntc-ts/tree/fix/ts-export)?

**Comment by j4mesli** [comment]
> @j4mesli Thanks for taking a crack at it!
> 
> Not sure why we need to duplicate `src/index.ts` to `src/ntc-ts.ts`, shouldn't the `type: module` fix it already on my [latest branch](https://github.com/Danetag/ntc-ts/tree/fix/ts-export)?

Sorry! My mistake, it does work properly just by changing the `type: module` line! I think I forgot to delete the file when I uploaded the changes and mixed it up... my mistake! It works as intended just from the `type: module` change!

```ts

```

**Comment by Danetag** [comment]
@j4mesli Gotcha! Well I added it in my [original PR](https://github.com/Danetag/ntc-ts/pull/24), feel free to review and approve and I'll merge/deploy a new version! 

Thanks again for your contribution 🙏

**Comment by j4mesli** [comment]
I'll get on it right away, thanks again!

**Pull request closed without merging**
